import './globals.css';
import type { Metadata } from 'next';

import { Poppins } from 'next/font/google';
import SessionExpiredSnackbar from '@/components/SessionExpiredSnackbar/SessionExpiredSnackbar';
import Providers from '@/providers';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Maloka'ai",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.variable}`}>
        <Providers>
          {children}
          <SessionExpiredSnackbar />
        </Providers>
      </body>
    </html>
  );
}
