name: Deploy para EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Instalar dependências e buildar
        run: |
          yarn install
          yarn build --no-lint

      - name: Preparar artefato para deploy
        run: |
          mkdir -p release
          cp -r .next public package.json yarn.lock next.config.js release/ 2>/dev/null || true
          # Incluir a pasta app se existir (Next.js App Router)
          [ -d app ] && cp -r app release/
          cd release
          tar -czf ../web-main.tar.gz .
          cd ..

      - name: Copiar artefato para EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "web-main.tar.gz"
          target: "/home/ubuntu/"

      - name: Deploy na EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            APP_DIR="/home/ubuntu/web-main"
            mkdir -p "$APP_DIR"
            rm -rf "$APP_DIR"/*
            tar -xzf /home/ubuntu/web-main.tar.gz -C "$APP_DIR"
            cd "$APP_DIR"

            echo "Instalando apenas dependências de produção com Yarn 3..."
            # Yarn 3+ usa 'workspaces focus' para produção
            yarn workspaces focus --production || yarn install --immutable --check-cache

            echo "Iniciando app via PM2..."
            pm2 delete web-main || true
            pm2 start "yarn start" --name web-main

            pm2 save
            pm2 list
