# .github/workflows/deploy.yaml
name: Deploy para EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executar script de deploy
        run: |
          cd /home/ubuntu/web-main
          ./deploy.sh
