name: Deploy para EC2

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Fazer checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # 3️⃣ Instalar dependências e buildar aplicação
      - name: Instalar dependências e buildar aplicação
        run: |
          yarn install --frozen-lockfile
          yarn build

      # 4️⃣ Preparar pacote (sem node_modules)
      - name: Preparar pacote para deploy
        run: |
          mkdir -p release
          cp -r .next public package.json yarn.lock release/
          cd release
          tar -czf ../web-main.tar.gz .
          mv ../web-main.tar.gz ..
          cd ..

      # 5️⃣ Copiar pacote para EC2
      - name: Copiar pacote para EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "web-main.tar.gz"
          target: "/home/ubuntu/"

      # 6️⃣ Executar deploy no servidor (com yarn install)
      - name: Executar deploy no servidor
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Garantir que o script de deploy está executável
            chmod +x /home/ubuntu/web-main/deploy.sh
            
            # Rodar o deploy
            /home/ubuntu/web-main/deploy.sh
            
            # Instalar dependências no servidor (se ainda não estiverem)
            cd /home/ubuntu/web-main
            yarn install --frozen-lockfile
