name: Build & Deploy Produção

on:
  push:
    tags:
      - 'v*'   # Somente tags de versão como v1.2.0

env:
  DOCKER_REGISTRY: ghcr.io/maloka-ai
  PROJECT_NAME: web-main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Definir tag de produção
        run: |
          PROD_TAG=${GITHUB_REF##*/}
          echo "PROD_TAG=$PROD_TAG" >> $GITHUB_ENV

      - name: Login no Docker GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build e Push da imagem Docker Next.js (.env.production)
        run: |
          IMAGE="${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_NAME }}:$PROD_TAG"
          echo "Building image $IMAGE"
          docker build --build-arg ENV_FILE=.env.production --no-cache -t $IMAGE .
          docker push $IMAGE

      - name: Clonar repositório de manifests
        uses: actions/checkout@v4
        with:
          repository: maloka-ai/gitops
          token: ${{ secrets.GHCR_TOKEN }}
          path: manifests

      - name: Atualizar tag da imagem no deploy.yaml de produção
        run: |
            cd manifests
            sed -i "s|^\(\s*image:\s*ghcr.io/maloka-ai/web-main:\).*|\1$PROD_TAG|" web-main/prod/deploy.yaml
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add web-main/prod/deploy.yaml
            if ! git diff --cached --quiet; then
              git commit -m "Atualiza web-main para $PROD_TAG em produção"
              git push
            else
              echo "Nenhuma alteração para commit/push."
            fi

      - name: Notificar no Discord de Implantação em Produção
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_ACTOR: ${{ github.actor }}
          PROD_TAG: ${{ env.PROD_TAG }}
        run: |
            COMMIT_HASH="${GITHUB_SHA::7}"
            COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
            DATE_MSG=$(TZ=America/Manaus date +"%d/%m/%Y %H:%M")
            
            MSG="🚀 *Deploy Produção*:\n\
            - 📦 **Aplicação:** WEB-MAIN \n\
            - 📦 **Imagem:** \`${{ env.DOCKER_REGISTRY }}/${{ env.PROJECT_NAME }}:${PROD_TAG}\`\n\
            - 📝 **Commit:** [${COMMIT_HASH}](https://github.com/${{ github.repository }}/commit/${GITHUB_SHA}) - ${COMMIT_MESSAGE}\n\
            - 👤 **Autor:** ${{ github.actor }}\n\
            - 🕓 **Horário:** ${DATE_MSG}"
            
            curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"$MSG\"}" "$DISCORD_WEBHOOK_URL"
