name: Deploy para EC2

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # 3. Instalar dependências
      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      # 4. Buildar aplicação
      - name: Buildar aplicação
        run: yarn build

      # 5. Preparar pacote para deploy
      - name: Preparar pacote
        run: |
          mkdir -p release
          cp -r .next public package.json yarn.lock node_modules release/
          cd release
          tar -czf ../web-main.tar.gz .
          cd ..

      # 6. Copiar pacote para EC2
      - name: Copiar pacote para EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "web-main.tar.gz"
          target: "/home/ubuntu/"

      # 7. Executar deploy no servidor
      - name: Executar deploy no servidor
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x /home/ubuntu/web-main/deploy.sh
            /home/ubuntu/web-main/deploy.sh
